server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API isteklerini backend'e yönlendirmek isterseniz burayı kullanabilirsiniz
    # Ancak şu anki yapıda frontend doğrudan 5000 portuna gittiği için gerek yok.
    
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
